#include "formats.h"

BLOCKDEVICE_FORMATDRIVER_EXTERN( coco_jvc );
BLOCKDEVICE_FORMATDRIVER_EXTERN( coco_vdk );
BLOCKDEVICE_FORMATDRIVER_EXTERN( coco_o9t );
BLOCKDEVICE_FORMATDRIVER_EXTERN( coco_vhd );
BLOCKDEVICE_FORMATDRIVER_EXTERN( coco_dmk );

BLOCKDEVICE_FORMATCHOICES_EXTERN( coco );
