#!/bin/bash
# This is a script which automates some of the operations needed for porting DOS
# MAME to Un*x.  Run it in a directory containing the latest MAME sources,
# unzipped with the -L option to make all the filenames lower case.  Also, you
# must specify a previous xmame release's source directory.  For example, here's
# what I would do in my ~/emulators directory to port 0.37b14:
#           mkdir xmame-0.37b14.1
#           cd xmame-0.37b14.1
#           unzip -L ../M37B14.ZIP
#           prep-new-mame ../xmame-0.37b13.2
#
# Lawrence Gold <gold@aros.net>
# Last modified on 11 April 2001.

# Fix the line endings of the included text and makefiles.
d2u `find . -name "*.txt" -print`
d2u `find . -name "*.mak" -print`

# Change // comments to /* */ pairs.  Some C compilers don't like //.
fix-comments `find . -name "*.c" -print`
fix-comments `find . -name "*.h" -print`

# Copy over the src/unix folder from a previous release.
if [ -d $1/src/unix ]; then
  cp -R $1/src/unix src
else
  echo "Cannot find src/unix in old xmame directory, exiting..."
  exit 1
fi

# Make some symlinks.
ln -s src/unix/cab .
ln -s src/unix/contrib .
ln -s src/unix/doc .
ln -s src/unix/install-sh .

# Move the MAME text files to the doc directory.
mv readme.txt doc/readme.mame
mv whatsnew.txt doc/changes.mame

# Rename the MAME makefile and fix its line endings.
mv makefile makefile.mame
d2u makefile.mame

# Copy over makefile.unix from the old xmame directory.
cp $1/makefile.unix .

# Clean up the files left over from d2u and fix-comments.
rm `find . -name "*~" -print`
rm `find . -name "*.orig" -print`
