
enum
{
	asr733_chr_region = REGION_GFX1
};

enum
{
	/* 8 bytes per character definition */
	asr733_single_char_len = 8,

	asr733_chr_region_len	= 128*asr733_single_char_len
};

extern struct GfxDecodeInfo asr733_gfxdecodeinfo[];

extern unsigned char asr733_palette[];
extern unsigned short asr733_colortable[];
enum
{
	asr733_palette_size = 2 /** 3*/,
	asr733_colortable_size = 1 * 2
};


extern PALETTE_INIT ( asr733 ) ;

void asr733_init(void);
int asr733_init_term(int unit, void (*int_callback)(int state));

void asr733_reset(int unit);

int asr733_cru_r(int offset, int unit);
void asr733_cru_w(int offset, int data, int unit);

 READ8_HANDLER(asr733_0_cru_r);
WRITE8_HANDLER(asr733_0_cru_w);

void asr733_refresh(struct mame_bitmap *bitmap, int unit, int x, int y);

void asr733_keyboard(int unit);

#define ASR733_KEY_PORTS																		\
	PORT_START	/* keys 1-16 */																	\
		PORT_BITX(0x0001, IP_ACTIVE_HIGH, IPT_KEYBOARD, "1",      KEYCODE_1, CODE_NONE)		\
		PORT_BITX(0x0002, IP_ACTIVE_HIGH, IPT_KEYBOARD, "2",      KEYCODE_2, CODE_NONE)		\
		PORT_BITX(0x0004, IP_ACTIVE_HIGH, IPT_KEYBOARD, "3",      KEYCODE_3, CODE_NONE)		\
		PORT_BITX(0x0008, IP_ACTIVE_HIGH, IPT_KEYBOARD, "4",      KEYCODE_4, CODE_NONE)		\
		PORT_BITX(0x0010, IP_ACTIVE_HIGH, IPT_KEYBOARD, "5",      KEYCODE_5, CODE_NONE)		\
		PORT_BITX(0x0020, IP_ACTIVE_HIGH, IPT_KEYBOARD, "6",      KEYCODE_6, CODE_NONE)		\
		PORT_BITX(0x0040, IP_ACTIVE_HIGH, IPT_KEYBOARD, "7",      KEYCODE_7, CODE_NONE)		\
		PORT_BITX(0x0080, IP_ACTIVE_HIGH, IPT_KEYBOARD, "8",      KEYCODE_8, CODE_NONE)		\
		PORT_BITX(0x0100, IP_ACTIVE_HIGH, IPT_KEYBOARD, "9",      KEYCODE_9, CODE_NONE)		\
		PORT_BITX(0x0200, IP_ACTIVE_HIGH, IPT_KEYBOARD, "0",      KEYCODE_0, CODE_NONE)		\
		PORT_BITX(0x0400, IP_ACTIVE_HIGH, IPT_KEYBOARD, ":",      KEYCODE_MINUS, CODE_NONE)	\
		PORT_BITX(0x0800, IP_ACTIVE_HIGH, IPT_KEYBOARD, "-",      KEYCODE_EQUALS, CODE_NONE)	\
		PORT_BITX(0x1000, IP_ACTIVE_HIGH, IPT_KEYBOARD, "ESC",    KEYCODE_ESC, CODE_NONE)		\
		PORT_BITX(0x2000, IP_ACTIVE_HIGH, IPT_KEYBOARD, "Q",      KEYCODE_Q, CODE_NONE)		\
		PORT_BITX(0x4000, IP_ACTIVE_HIGH, IPT_KEYBOARD, "W",      KEYCODE_W, CODE_NONE)		\
		PORT_BITX(0x8000, IP_ACTIVE_HIGH, IPT_KEYBOARD, "E",      KEYCODE_E, CODE_NONE)		\
																								\
	PORT_START	/* keys 17-32 */																\
		PORT_BITX(0x0001, IP_ACTIVE_HIGH, IPT_KEYBOARD, "R",      KEYCODE_R, CODE_NONE)		\
		PORT_BITX(0x0002, IP_ACTIVE_HIGH, IPT_KEYBOARD, "T",      KEYCODE_T, CODE_NONE)		\
		PORT_BITX(0x0004, IP_ACTIVE_HIGH, IPT_KEYBOARD, "Y",      KEYCODE_Y, CODE_NONE)		\
		PORT_BITX(0x0008, IP_ACTIVE_HIGH, IPT_KEYBOARD, "U",      KEYCODE_U, CODE_NONE)		\
		PORT_BITX(0x0010, IP_ACTIVE_HIGH, IPT_KEYBOARD, "I",      KEYCODE_I, CODE_NONE)		\
		PORT_BITX(0x0020, IP_ACTIVE_HIGH, IPT_KEYBOARD, "O",      KEYCODE_O, CODE_NONE)		\
		PORT_BITX(0x0040, IP_ACTIVE_HIGH, IPT_KEYBOARD, "P",      KEYCODE_P, CODE_NONE)		\
		PORT_BITX(0x0080, IP_ACTIVE_HIGH, IPT_KEYBOARD, "LINE FEED",KEYCODE_CLOSEBRACE, CODE_NONE)	\
		PORT_BITX(0x0100, IP_ACTIVE_HIGH, IPT_KEYBOARD, "RETURN", KEYCODE_ENTER, CODE_NONE)	\
		PORT_BITX(0x0200, IP_ACTIVE_HIGH, IPT_KEYBOARD, "CTRL",   KEYCODE_LCONTROL, CODE_NONE)	\
		PORT_BITX(0x0400, IP_ACTIVE_HIGH, IPT_KEYBOARD, "A",      KEYCODE_A, CODE_NONE)		\
		PORT_BITX(0x0800, IP_ACTIVE_HIGH, IPT_KEYBOARD, "S",      KEYCODE_S, CODE_NONE)		\
		PORT_BITX(0x1000, IP_ACTIVE_HIGH, IPT_KEYBOARD, "D",      KEYCODE_D, CODE_NONE)		\
		PORT_BITX(0x2000, IP_ACTIVE_HIGH, IPT_KEYBOARD, "F",      KEYCODE_F, CODE_NONE)		\
		PORT_BITX(0x4000, IP_ACTIVE_HIGH, IPT_KEYBOARD, "G",      KEYCODE_G, CODE_NONE)		\
		PORT_BITX(0x8000, IP_ACTIVE_HIGH, IPT_KEYBOARD, "H",      KEYCODE_H, CODE_NONE)		\
																								\
	PORT_START	/* keys 33-48 */																\
		PORT_BITX(0x0001, IP_ACTIVE_HIGH, IPT_KEYBOARD, "J",      KEYCODE_J, CODE_NONE)		\
		PORT_BITX(0x0002, IP_ACTIVE_HIGH, IPT_KEYBOARD, "K",      KEYCODE_K, CODE_NONE)		\
		PORT_BITX(0x0004, IP_ACTIVE_HIGH, IPT_KEYBOARD, "L",      KEYCODE_L, CODE_NONE)		\
		PORT_BITX(0x0008, IP_ACTIVE_HIGH, IPT_KEYBOARD, ";",      KEYCODE_COLON, CODE_NONE)	\
		PORT_BITX(0x0010, IP_ACTIVE_HIGH, IPT_KEYBOARD, "RUB OUT",KEYCODE_BACKSPACE, CODE_NONE)	\
		PORT_BITX(0x0020, IP_ACTIVE_HIGH, IPT_KEYBOARD, "REPEAT", KEYCODE_RALT, CODE_NONE)	\
		/* hack for my mac that does not disciminate the right ALT key */						\
		PORT_BITX(0x0020, IP_ACTIVE_HIGH, IPT_KEYBOARD, "REPEAT", KEYCODE_LALT, CODE_NONE)	\
		PORT_BITX(0x0040, IP_ACTIVE_HIGH, IPT_KEYBOARD, "SHIFT",  KEYCODE_LSHIFT, CODE_NONE)	\
		PORT_BITX(0x0080, IP_ACTIVE_HIGH, IPT_KEYBOARD, "Z",      KEYCODE_Z, CODE_NONE)		\
		PORT_BITX(0x0100, IP_ACTIVE_HIGH, IPT_KEYBOARD, "X",      KEYCODE_X, CODE_NONE)		\
		PORT_BITX(0x0200, IP_ACTIVE_HIGH, IPT_KEYBOARD, "C",      KEYCODE_C, CODE_NONE)		\
		PORT_BITX(0x0400, IP_ACTIVE_HIGH, IPT_KEYBOARD, "V",      KEYCODE_V, CODE_NONE)		\
		PORT_BITX(0x0800, IP_ACTIVE_HIGH, IPT_KEYBOARD, "B",      KEYCODE_B, CODE_NONE)		\
		PORT_BITX(0x1000, IP_ACTIVE_HIGH, IPT_KEYBOARD, "N",      KEYCODE_N, CODE_NONE)		\
		PORT_BITX(0x2000, IP_ACTIVE_HIGH, IPT_KEYBOARD, "M",      KEYCODE_M, CODE_NONE)		\
		PORT_BITX(0x4000, IP_ACTIVE_HIGH, IPT_KEYBOARD, ",",      KEYCODE_COMMA, CODE_NONE)	\
		PORT_BITX(0x8000, IP_ACTIVE_HIGH, IPT_KEYBOARD, ".",      KEYCODE_STOP, CODE_NONE)	\
																								\
	PORT_START	/* keys 49-51 */																\
		PORT_BITX(0x0001, IP_ACTIVE_HIGH, IPT_KEYBOARD, "/",      KEYCODE_SLASH, CODE_NONE)	\
		PORT_BITX(0x0002, IP_ACTIVE_HIGH, IPT_KEYBOARD, "SHIFT",  KEYCODE_RSHIFT, CODE_NONE)	\
		PORT_BITX(0x0004, IP_ACTIVE_HIGH, IPT_KEYBOARD, "(SPACE)", KEYCODE_SPACE, CODE_NONE)
